### ISSUE TITLE
Move STEAM's blog to internal.k8s cluster

### ISSUE THREAD

**Issue by exklamationmark** [steamforvietnam/devops#18]
What type of issue is this?
----------------------------------
- App deployment/upgrade

What is the issue/problem?
------------------------------------
Move STEAM's blog to a shared cluster, so the cluster can use resources more efficiently.

### Context
- We have a [k8s cluster](https://cloud.digitalocean.com/kubernetes/clusters/776e5a23-ce17-464f-9393-70a0065b78a0?i=2b4d6e) to solely run the STEAM's blog.
- This cluster have severly underutilized nodes:
  - [worker-1](https://cloud.digitalocean.com/droplets/217752195/graphs?i=2b4d6e&period=hour)
  - [worker-2](https://cloud.digitalocean.com/droplets/217752194/graphs?i=2b4d6e&period=hour)
- We want to move this blog workload to a shared cluster, so we have higher utilization.

### Requirements
- [ ] Define steps to migrate the blog.
- [ ] Announce the migration in #engineering-team (and #general)
- [ ] Execute the migration

Is there any suggestions for the implementation?
-----------------------------------------------------------------
- The blog run as a wordpress deployment, connecting to a database. You will need a plan to migrate this DB (downtime is okay).
- The blog have are currently exposed through public Internet. [Some apps use this IP to redirect to the blog](https://github.com/search?q=org%3Asteamforvietnam+139.59.219.11&type=code).
  - You would need to make PRs to those apps to get them to work properly.
  - When you move, use `external-dns` to add the host: `blog.steamforvietnam.org`.
```
$> k get svc
NAME                TYPE           CLUSTER-IP       EXTERNAL-IP     PORT(S)                      AGE
wordpress           LoadBalancer   10.245.161.81    139.59.219.11   80:31951/TCP,443:30978/TCP   300d
```

**Comment by kutycoi123** [comment]
The website is successfully migrated to this IP: http://137.184.248.4/
Next step: Update apps to use this new IP

**Comment by exklamationmark** [comment]
migrated
